"""LangGraph State schema definition for TARS orchestration pipeline.

Defines the central state dictionary that transitions through the StateGraph.
"""

from __future__ import annotations

from typing import Annotated, Any

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

from tars.adapters.base import ToolCallData
from tars.core.okf.models import OKFDocument

# Default persona and execution configuration constants
DEFAULT_HUMOR_LEVEL: float = 0.90
DEFAULT_HONESTY_LEVEL: float = 0.95
DEFAULT_MODE: str = "companion"
DEFAULT_MAX_TOOL_ITERATIONS: int = 5


class TARSState(TypedDict, total=False):
    """Complete LangGraph StateGraph schema for TARS orchestration pipeline.

    Attributes:
        messages: Conversation message history with LangGraph add_messages reducer.
        user_id: Unique user identifier for storage and DB partitioning.
        session_id: Active dialogue session ID for memory checkpointing.
        humor_level: TARS humor parameter in range [0.0, 1.0] (default: 0.90).
        honesty_level: TARS honesty parameter in range [0.0, 1.0] (default: 0.95).
        mode: Operational mode ('companion' for TARS dry wit vs. 'work' for CASE precision).
        relevant_wikis: List of sliced OKFDocument knowledge objects injected into context.
        system_prompt: Dynamically composed system prompt with persona and OKF XML context.
        final_response: Accumulated text response generated by the LLM for the current turn.
        tool_calls: Pending or executed structured tool invocations.
        tool_results: List of execution outcome dictionaries from tool_node.
        iteration_count: Current loop iteration count in ReAct StateGraph.
        error_message: Graceful fallback error details if tool execution failed.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    user_id: str
    session_id: str
    humor_level: float
    honesty_level: float
    mode: str
    relevant_wikis: list[OKFDocument]
    system_prompt: str
    final_response: str
    tool_calls: list[ToolCallData]
    tool_results: list[dict[str, Any]]
    iteration_count: int
    error_message: str | None


__all__ = [
    "DEFAULT_HONESTY_LEVEL",
    "DEFAULT_HUMOR_LEVEL",
    "DEFAULT_MAX_TOOL_ITERATIONS",
    "DEFAULT_MODE",
    "TARSState",
]
