"""LangGraph State schema definition for TARS orchestration pipeline.

Defines the central state dictionary that transitions through the StateGraph.
"""

from __future__ import annotations

from typing import Annotated, Any

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

from tars.adapters.base import ToolCallData
from tars.core.okf.models import OKFDocument
from tars.core.session.models import RoutingDecision

# Default persona and execution configuration constants
DEFAULT_HUMOR_LEVEL: float = 0.90
DEFAULT_HONESTY_LEVEL: float = 0.95
DEFAULT_MODE: str = "companion"
DEFAULT_MAX_TOOL_ITERATIONS: int = 5


class TARSState(TypedDict, total=False):
    """Complete LangGraph StateGraph schema for TARS orchestration pipeline.

    Attributes:
        messages: Conversation message history with LangGraph add_messages reducer
            (SystemMessage excluded, only Human/AI/ToolMessage accumulated).
        user_id: Unique user identifier for storage and DB partitioning.
        session_id: Active dialogue session ID for memory checkpointing.
        active_query: Current user query string being processed in this turn.
        humor_level: TARS humor parameter in range [0.0, 1.0] (default: 0.90).
        honesty_level: TARS honesty parameter in range [0.0, 1.0] (default: 0.95).
        mode: Operational mode ('companion' for TARS dry wit vs. 'work' for CASE precision).
        routing_decision: Output summary of session routing evaluation.
        is_reset: Boolean flag indicating if current turn is a natural language reset command.
        reset_message: Notice message presented to user upon session archiving/reset.
        relevant_wikis: List of sliced OKFDocument knowledge objects injected into context.
        system_prompt: Dynamically composed system prompt with persona and OKF XML context
            (strictly isolated from messages list).
        tool_calls: Pending or executed structured tool invocations.
        tool_results: List of execution outcome dictionaries from tool_node.
        iteration_count: Current loop iteration count in ReAct StateGraph.
        final_response: Accumulated text response generated by the LLM for the current turn.
        tools_used: List of tool names executed during this turn.
        error_message: Graceful fallback error details if tool execution failed.
    """

    # 1. 대화 메시지 (SystemMessage 제외, Human/AI/ToolMessage만 누적)
    messages: Annotated[list[BaseMessage], add_messages]
    user_id: str
    session_id: str
    active_query: str

    # 2. 페르소나 파라미터
    humor_level: float
    honesty_level: float
    mode: str

    # 3. 세션 라우팅 및 제어
    routing_decision: RoutingDecision | None
    is_reset: bool
    reset_message: str | None

    # 4. 동적 지식 및 프롬프트 (메시지 리스트와 엄격히 분리 격리)
    relevant_wikis: list[OKFDocument]
    system_prompt: str

    # 5. ReAct 실행 및 도구 추적
    tool_calls: list[ToolCallData]
    tool_results: list[dict[str, Any]]
    iteration_count: int
    final_response: str
    tools_used: list[str]
    error_message: str | None


__all__ = [
    "DEFAULT_HONESTY_LEVEL",
    "DEFAULT_HUMOR_LEVEL",
    "DEFAULT_MAX_TOOL_ITERATIONS",
    "DEFAULT_MODE",
    "TARSState",
]
