"""Data schemas for OKF relevance scanning and candidate extraction."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from tars.domains.knowledge.spec.schemas import OKFImportance, OKFType
from tars.domains.proactive.schemas import ScheduleType


class DeadlineExtractionResult(BaseModel):
    """Structured extraction of actionable deadlines from OKF content.

    Zero-regex standard: Generated by LLM structured outputs or semantic inference.
    """

    model_config = ConfigDict(extra="ignore")

    has_deadline: bool = Field(
        description="Whether the document contains any actionable deadline or review date"
    )
    deadline_utc: datetime | None = Field(
        default=None,
        description="Extracted deadline converted to UTC timezone. None if no deadline detected.",
    )
    deadline_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence score of the extracted deadline (0=uncertain, 1=explicit date)",
    )
    review_cycle_days: int | None = Field(
        default=None,
        description="Suggested review interval in days inferred from content, or None",
    )


class UtteranceCandidate(BaseModel):
    """Candidate document or context evaluated by the threshold scorer."""

    model_config = ConfigDict(extra="ignore")

    user_id: str
    schedule_type: ScheduleType
    okf_id: str | None = None
    title: str | None = None
    okf_type: OKFType | None = None
    importance: OKFImportance = OKFImportance.MEDIUM
    elapsed_days: float = 0.0
    review_cycle_days: int = 7
    has_conversation_context: bool = False
    deadline_utc: datetime | None = None
    raw_document_summary: str | None = None


class ScanResult(BaseModel):
    """Aggregate result from scanning OKF documents and user state."""

    model_config = ConfigDict(extra="ignore")

    user_id: str
    scanned_count: int
    candidates: list[UtteranceCandidate]
    scanned_at_utc: datetime


__all__ = [
    "DeadlineExtractionResult",
    "ScanResult",
    "UtteranceCandidate",
]
