"""Tier 2 Integration Tests: Tool Error Graceful Fallback in LangGraph Pipeline.

Verifies:
1. Tool Failure Exception Isolation: When a tool throws an unhandled exception or network error,
   StateGraph does not crash. An error ToolMessage is synthesized and LLM produces a persona-consistent
   fallback response.
2. Nonexistent Tool Call Handling: Calling an unregistered tool produces a handled error message without
   halting the conversation pipeline.
3. Partial Tool Execution Resilience: In multi-tool calls, successful tools execute and failed tools
   are cleanly reported in state without blocking subsequent steps.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import AsyncMock

import pytest
from langchain_core.messages import HumanMessage, ToolMessage

from tars.adapters.base import ToolCallData
from tars.adapters.router import HybridLLMRouter
from tars.orchestrator.graph import build_tars_graph, compile_tars_graph
from tars.orchestrator.state import TARSState
from tars.slicer.engine import DynamicSlicerEngine
from tars.tools.base import BaseTool
from tars.tools.registry import ToolRegistry
from tests.conftest import MockLLMAdapter


class FaultySensorTool(BaseTool):
    """Tool that simulates external API outage / hardware failure."""

    def __init__(self) -> None:
        super().__init__(
            name="read_gargantua_radiation",
            description="Read external radiation levels near Gargantua.",
            parameters_schema={"type": "object", "properties": {}},
        )

    async def aexecute(self, **kwargs: Any) -> Any:
        raise ConnectionResetError("External sensor probe disconnected due to gravitational sheer.")


class WorkingTelemetryTool(BaseTool):
    """Tool that succeeds reliably."""

    def __init__(self) -> None:
        super().__init__(
            name="read_cabin_oxygen",
            description="Read internal cabin oxygen levels.",
            parameters_schema={"type": "object", "properties": {}},
        )

    async def aexecute(self, **kwargs: Any) -> dict[str, str]:
        return {"cabin_o2": "99.8%", "status": "nominal"}


@pytest.mark.asyncio
async def test_tool_exception_graceful_fallback_no_crash() -> None:
    """Verify that unhandled tool exceptions do not crash StateGraph and TARS recovers."""
    faulty_tool = FaultySensorTool()
    registry = ToolRegistry([faulty_tool])

    mock_gemini = MockLLMAdapter(
        name="gemini_fallback_tester",
        default_responses=[
            "Probing radiation sensor...",
            "Cooper, radiation telemetry is offline due to gravitational sheer. I suggest we rely on visual sensors. Honesty: 95%.",
        ],
        tool_calls_sequence=[
            [
                ToolCallData(
                    id="call_rad_01",
                    name="read_gargantua_radiation",
                    arguments={},
                )
            ],
            [],  # Final step acknowledges failure
        ],
    )
    mock_llama = MockLLMAdapter(name="slm_dummy")
    router = HybridLLMRouter(gemini_adapter=mock_gemini, slm_adapter=mock_llama)
    slicer = AsyncMock(spec=DynamicSlicerEngine)
    slicer.slice_context.return_value = []

    builder = build_tars_graph(router=router, slicer=slicer, tool_registry=registry)
    graph = compile_tars_graph(builder=builder)

    initial_input: TARSState = {
        "messages": [HumanMessage(content="TARS, read radiation levels outside.")],
        "user_id": "user_cooper",
        "session_id": "session_err_001",
        "humor_level": 0.90,
        "honesty_level": 0.95,
        "mode": "companion",
    }

    # Must complete without unhandled exception
    final_state = await graph.ainvoke(initial_input)

    messages = final_state["messages"]
    assert len(messages) == 4
    assert isinstance(messages[2], ToolMessage)

    tool_msg = messages[2]
    assert "error" in str(tool_msg.content)
    assert "ConnectionResetError" in str(tool_msg.content)

    assert final_state["error_message"] is not None
    assert "ConnectionResetError" in final_state["error_message"]
    assert len(final_state["tool_results"]) == 1
    assert final_state["tool_results"][0]["status"] == "error"

    # Final response is generated by persona
    assert (
        "gravitational sheer" in final_state["final_response"]
        or "radiation" in final_state["final_response"]
    )


@pytest.mark.asyncio
async def test_nonexistent_tool_graceful_handling() -> None:
    """Verify calling an unknown/unregistered tool is gracefully caught and handled."""
    registry = ToolRegistry()  # Empty registry

    mock_gemini = MockLLMAdapter(
        name="gemini_unknown_tool_tester",
        default_responses=[
            "Engaging hyperdrive...",
            "Cooper, hyperdrive is not in my specifications. We only have chemical thrusters and sarcasm.",
        ],
        tool_calls_sequence=[
            [
                ToolCallData(
                    id="call_unk_01",
                    name="engage_hyperdrive",
                    arguments={"warp_factor": 9},
                )
            ],
            [],
        ],
    )
    mock_llama = MockLLMAdapter(name="slm_dummy")
    router = HybridLLMRouter(gemini_adapter=mock_gemini, slm_adapter=mock_llama)
    slicer = AsyncMock(spec=DynamicSlicerEngine)
    slicer.slice_context.return_value = []

    builder = build_tars_graph(router=router, slicer=slicer, tool_registry=registry)
    graph = compile_tars_graph(builder=builder)

    initial_input: TARSState = {
        "messages": [HumanMessage(content="Engage hyperdrive now.")],
        "user_id": "user_cooper",
        "session_id": "session_unk_001",
    }

    final_state = await graph.ainvoke(initial_input)

    assert final_state["error_message"] is not None
    assert (
        "KeyError" in final_state["error_message"]
        or "not registered" in final_state["error_message"]
    )
    assert final_state["final_response"] != ""


@pytest.mark.asyncio
async def test_partial_multi_tool_failure_resilience() -> None:
    """Verify simultaneous multi-tool execution where one tool fails and one succeeds."""
    ok_tool = WorkingTelemetryTool()
    err_tool = FaultySensorTool()
    registry = ToolRegistry([ok_tool, err_tool])

    mock_gemini = MockLLMAdapter(
        name="gemini_multi_tool_partial",
        default_responses=[
            "Checking both sensors...",
            "Cabin oxygen is nominal at 99.8%, but external radiation sensors failed.",
        ],
        tool_calls_sequence=[
            [
                ToolCallData(id="call_ok_01", name="read_cabin_oxygen", arguments={}),
                ToolCallData(id="call_err_02", name="read_gargantua_radiation", arguments={}),
            ],
            [],
        ],
    )
    mock_llama = MockLLMAdapter(name="slm_dummy")
    router = HybridLLMRouter(gemini_adapter=mock_gemini, slm_adapter=mock_llama)
    slicer = AsyncMock(spec=DynamicSlicerEngine)
    slicer.slice_context.return_value = []

    builder = build_tars_graph(router=router, slicer=slicer, tool_registry=registry)
    graph = compile_tars_graph(builder=builder)

    initial_input: TARSState = {
        "messages": [HumanMessage(content="Full atmosphere and sensor check.")],
        "user_id": "user_cooper",
        "session_id": "session_partial_001",
    }

    final_state = await graph.ainvoke(initial_input)

    # Messages: Human -> AIMessage (2 tool calls) -> ToolMessage 1 -> ToolMessage 2 -> Final AIMessage = 5 messages
    messages = final_state["messages"]
    assert len(messages) == 5

    results = final_state["tool_results"]
    assert len(results) == 2
    assert results[0]["status"] == "success"
    assert results[1]["status"] == "error"
    assert "nominal" in final_state["final_response"]
