apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    hostNetwork: true
    deployment:
      dnsPolicy: ClusterFirstWithHostNet
    podSecurityContext:
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop: []
        add:
          - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
    ports:
      web:
        port: 80
        exposedPort: 80
      websecure:
        port: 443
        exposedPort: 443
    service:
      spec:
        type: ClusterIP
