apiVersion: v1
kind: ConfigMap
metadata:
  name: tars-config
  namespace: tars
data:
  TARS_ENVIRONMENT: "production"
  TARS_STORAGE_DIR: "/app/storage"
  TARS_DOMAIN: "localhost"
  TARS_GEMINI_MODEL_NAME: "gemini-3.7-flash"
  TARS_LLAMACPP_BASE_URL: "http://gemma-4-12b-service.default.svc.cluster.local:8080/v1"
  POSTGRES_DB: "tars"
  POSTGRES_USER: "tarsuser"
  TARS_LANGFUSE_ENABLED: "true"
  TARS_LANGFUSE_HOST: "http://langfuse-web:3000"
  TARS_STORAGE_BACKEND: "s3"
  TARS_S3_ENDPOINT_URL: "http://seaweedfs-s3.tars.svc.cluster.local:8333"
  TARS_S3_BUCKET_NAME: "tars-okf"
  TARS_S3_REGION: "us-east-1"

